// watchlist types
export const GET_WATCHLISTS = 'GET_WATCHLISTS';
export const GET_WATCHLISTS_LOADING = 'GET_WATCHLISTS_LOADING';
export const GET_WATCHLISTS_ERROR = 'GET_WATCHLISTS_ERROR';
export const CREATE_WATCHLIST = 'CREATE_WATCHLIST';
export const ADD_TICKER_TO_WATCHLIST = "ADD_TICKER_TO_WATCHLIST";
export const ASSET_LOADING = 'ASSET_LOADING';
export const ASSET_ERROR = 'ASSET_ERROR';
export const REMOVE_ASSET_FROM_WATCHLIST = 'REMOVE_ASSET_FROM_WATCHLIST';
export const GET_CURRENT_WATCHLIST_ID = 'GET_CURRENT_WATCHLIST_ID';
export const GET_WATCHLIST = 'GET_WATCHLIST';
export const WATCHLIST_LOADING = 'WATCHLIST_LOADING';
// Tickers
export const GET_TICKER = 'GET_TICKER';
export const TICKER_LOADING = 'TICKER_LOADING';
export const TICKER_ERROR = 'TICKER_ERROR';
export const CLEAR_TICKER = 'CLEAR_TICKER';
export const CLEAR_TICKER_ERROR = 'CLEAR_TICKER_ERROR';
//Asset
export const GET_ASSET = 'GET_ASSET';
export const ASSET_DETAIL_ERROR = 'ASSET_DETAIL_ERROR';
export const ASSET_DETAIL_LOADING = 'ASSET_DETAIL_LOADING';
// signin 
export const USER_LOADING = 'USER_LOADING';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
export const USER_SIGNOUT_FAILURE = 'USER_SIGNOUT_FAILURE';
// Account 
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING';